Milestone 1

Nama  : Rofi'ah Budi Nadia
Batch : CODA-RMT-019

Program ini dibuat untuk melakukan pengambilan data dari halaman website footlocker menggunakan library selenium, kemudian diolah dan disimpan ke dalam database PostgreSQL.

In [22]:
# data manipulation or dataframe
import pandas as pd
import time

# webscraping
from selenium import webdriver
from bs4 import BeautifulSoup
from urllib.parse import urljoin

Import semua library yang akan digunakan untuk data manipulation dan webscrapping menggunakan selenium

In [23]:
# empty list
names = []
brands = []
prices = []
categories = []
colors = []
boxes = []

# create driver
driver = webdriver.Chrome()

for page in range(1, 4):
    url = f'https://www.footlocker.id/catalogsearch/result/?p={page}&q=shoes'
    driver.get(url)
    time.sleep(10)

    # fetch html components
    html = driver.page_source

    # parse
    soup = BeautifulSoup(html, "html.parser")

    boxes = soup.find_all('li', {'class':'product-card item product product-item'})

    # <a class="product-item-link" href="https://www.footlocker.id/speedcat-og-unisex-lifestyle-shoes-black-16.html" data-item-page="1">Speedcat OG Unisex Lifestyle Shoes - Black                </a>
    #
    for box in boxes:
        try:
            el_name = box.find('a', {'class':'product-item-link'})
            names.append(el_name.get_text())
        except:
            names.append(None)

        try:
            el_brand = box.find('h3', {'class':'product-brand'})
            brands.append(el_brand.get_text())
        except:
            names.append(None)
        
        try:
            el_price = box.find('span', {'data-price-type':'finalPrice'})
            prices.append(el_price.get_text())
        except:
            prices.append(None)

        try:
            el_categorie = box.find('div', {'class':'gender'})
            categories.append(el_categorie.get_text())
        except:
            prices.append(None)

        try:
            el_color = box.find('span', {'class':'value'})
            colors.append(el_color.get_text())
        except:
            colors.append(None)

driver.quit()

Melakukan scrapping dengan menggunakan library selenium, dengan method halaman page yaitu looping untuk setiap pagenya, disini saya mengambil 3 page karena dirasa sudah cukup untuk mendapat lebih dari 50 data dengan mengatur time.sleep ke 10s, dengan get.element yaitu nama produk, merk, harga, kategori, dan juga warna (5 columns)
Menggunakan method try except karena apabila dalam 1 row terdapat element yang tidak ada maka akan di append sebagai NaN

In [24]:
# create a dataframe
df = pd.DataFrame(
    {
        'nama produk':names,
        'merk':brands,
        'harga':prices,
        'kategori':categories,
        'warna':colors
    }
)

Membuat dataframe yang berisi 5 kolom yaitu nama produk, merk, harga, kategori, dan warna

In [25]:
df

,nama produk,merk,harga,kategori,warna
0,\n Cloud 6 Women's Sneakers...,\nON\n,\n\n Rp...,Wanita,Putih
1,\n 530 Unisex Sneakers - Si...,\nNEW BALANCE\n,\n\n Rp...,Unisex,Abu-abu
2,\n 530 Unisex Sneakers - Si...,\nNEW BALANCE\n,\n\n Rp...,Unisex,Abu-abu
3,\n 740 Unisex Sneakers - Be...,\nNEW BALANCE\n,\n\n Rp...,Unisex,Beige
4,\n 740 Unisex Sneakers - Qu...,\nNEW BALANCE\n,\n\n Rp...,Unisex,Abu-abu
...,...,...,...,...,...
79,\n x SHAI 001 Men's Sneaker...,\nCONVERSE\n,\n\n Rp...,Pria,Pink
80,\n x SHAI 001 Men's Sneaker...,\nCONVERSE\n,\n\n Rp...,Unisex,Putih
81,\n GT-2160 Breeze Unisex Sn...,\nASICS\n,\n\n Rp...,Unisex,Putih
82,\n Zoom Vomero 5 Men's Snea...,\nNike\n,\n\n Rp...,Pria,Abu-abu
83,\n Reactx Rejuven8 Kids' Gr...,\nNike\n,\n\n Rp. 86...,Anak - Anak,Biru

Menampilkan dataframe yang telah dibuat

In [26]:
df.to_csv('data-kotor.csv', index=False)

Menyimpan data kotor yang sudah didapat dari hasil scrapping di .csv
index=false yaitu artinya kolom untuk indexnya tidak ada atau tidak diikutsertakan

In [27]:
df = pd.read_csv('data-kotor.csv')

Membaca atau load data .csv yang sudah disimpan, data ini yang akan digunakan untuk eksplorasi

In [28]:
df.head()

,nama produk,merk,harga,kategori,warna
0,\n Cloud 6 Women's Sneakers...,\nON\n,\n\n Rp...,Wanita,Putih
1,\n 530 Unisex Sneakers - Si...,\nNEW BALANCE\n,\n\n Rp...,Unisex,Abu-abu
2,\n 530 Unisex Sneakers - Si...,\nNEW BALANCE\n,\n\n Rp...,Unisex,Abu-abu
3,\n 740 Unisex Sneakers - Be...,\nNEW BALANCE\n,\n\n Rp...,Unisex,Beige
4,\n 740 Unisex Sneakers - Qu...,\nNEW BALANCE\n,\n\n Rp...,Unisex,Abu-abu

Menampilkan 5 data teratas dari dataframe

In [29]:
df.tail()

,nama produk,merk,harga,kategori,warna
79,\n x SHAI 001 Men's Sneaker...,\nCONVERSE\n,\n\n Rp...,Pria,Pink
80,\n x SHAI 001 Men's Sneaker...,\nCONVERSE\n,\n\n Rp...,Unisex,Putih
81,\n GT-2160 Breeze Unisex Sn...,\nASICS\n,\n\n Rp...,Unisex,Putih
82,\n Zoom Vomero 5 Men's Snea...,\nNike\n,\n\n Rp...,Pria,Abu-abu
83,\n Reactx Rejuven8 Kids' Gr...,\nNike\n,\n\n Rp. 86...,Anak - Anak,Biru

Menampilkan 5 data terbawah dari dataframe

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   nama produk  84 non-null     object
 1   merk         84 non-null     object
 2   harga        84 non-null     object
 3   kategori     84 non-null     object
 4   warna        82 non-null     object
dtypes: object(5)
memory usage: 3.4+ KB

Menampilkan informasi dari data tersebut :
- terdapat 84 rows data
- terdapat 5 column
- columns nama produk, merk, kategori, dan warna bertipe data object
- column harga bertipe data integer
- pada column warna terdapat 82 rows yang non-null, artinya terdapat 2 rows yang null

In [31]:
df['harga'].unique()

array(['\n\n                                        Rp. 1.500.000                                    \n',
       '\n\n                                        Rp. 1.019.400                                    \n',
       '\n\n                                        Rp. 1.189.300                                    \n',
       '\n\n                                        Rp. 949.500                                    \n',
       '\n\n                                        Rp. 545.400                                    \n',
       '\n\n                                        Rp. 1.119.200                                    \n',
       '\n\n                                    Rp. 999.000                                \n',
       '\n\n                                        Rp. 900.000                                    \n',
       '\n\n                                    Rp. 1.429.000                                \n',
       '\n\n                                        Rp. 1.000.000                                    \n',
       '\n\n                                        Rp. 700.000                                    \n',
       '\n\n                                    Rp. 1.099.000                                \n',
       '\n\n                                        Rp. 450.000                                    \n',
       '\n\n                                    Rp. 850.000                                \n',
       '\n\n                                        Rp. 800.000                                    \n',
       '\n\n                                        Rp. 595.000                                    \n',
       '\n\n                                        Rp. 659.400                                    \n',
       '\n\n                                        Rp. 1.959.300                                    \n',
       '\n\n                                        Rp. 799.500                                    \n',
       '\n\n                                        Rp. 499.500                                    \n',
       '\n\n                                        Rp. 1.540.000                                    \n',
       '\n\n                                        Rp. 995.400                                    \n',
       '\n\n                                        Rp. 1.099.500                                    \n',
       '\n\n                                        Rp. 695.200                                    \n',
       '\n\n                                        Rp. 677.400                                    \n',
       '\n\n                                        Rp. 1.084.300                                    \n',
       '\n\n                                        Rp. 2.400.000                                    \n',
       '\n\n                                        Rp. 455.400                                    \n',
       '\n\n                                        Rp. 599.500                                    \n',
       '\n\n                                        Rp. 1.560.000                                    \n',
       '\n\n                                    Rp. 759.000                                \n',
       '\n\n                                        Rp. 864.500                                    \n',
       '\n\n                                        Rp. 779.400                                    \n',
       '\n\n                                    Rp. 2.399.000                                \n',
       '\n\n                                    Rp. 2.800.000                                \n',
       '\n\n                                    Rp. 2.700.000                                \n',
       '\n\n                                    Rp. 2.199.000                                \n',
       '\n\n                                        Rp. 699.500                                    \n',
       '\n\n                                    Rp. 2.499.000                                \n',
       '\n\n                                        Rp. 2.309.300                                    \n',
       '\n\n                                    Rp. 800.000                                \n',
       '\n\n                                        Rp. 749.500                                    \n',
       '\n\n                                        Rp. 379.500                                    \n',
       '\n\n                                        Rp. 649.500                                    \n',
       '\n\n                                        Rp. 1.399.300                                    \n',
       '\n\n                                    Rp. 1.129.000                                \n',
       '\n\n                                        Rp. 624.500                                    \n',
       '\n\n                                    Rp. 1.199.000                                \n',
       '\n\n                                    Rp. 1.500.000                                \n',
       '\n\n                                        Rp. 1.783.200                                    \n',
       '\n\n                                        Rp. 769.300                                    \n',
       '\n\n                                        Rp. 737.400                                    \n',
       '\n\n                                        Rp. 574.500                                    \n',
       '\n\n                                        Rp. 2.699.000                                    \n',
       '\n\n                                        Rp. 1.049.500                                    \n',
       '\n\n                                        Rp. 1.493.400                                    \n',
       '\n\n                                    Rp. 869.000                                \n'],
      dtype=object)

Disini saya melihat ada yang belum bersih di value pada columns 'nama produk', 'merk', dan 'harga'
pertama saya melihat unique value dari column 'harga'
terlihat bahwa banyak character yang tidak perlu(space) dalam rows value tersebut
maka selanjutnya saya akan menghapus character space tersebut

In [32]:
try:
    df['harga'] = df['harga'].str.replace('\n\n                                        Rp. ', '')
except:
    pass

try:
    df['harga'] = df['harga'].str.replace('\n\n                                    Rp. ', '')
except:
    pass

try:
    df['harga'] = df['harga'].str.replace('                                    \n', '')
except:
    pass

try:
    df['harga'] = df['harga'].str.replace('                                \n', '')
except:
    pass

df['harga'] = df['harga'] = df['harga'].str.replace('.', '').astype(int)
# df['harga'].astype(int)

Melakukan cleaning pada column 'harga' yaitu mengubah semua space menjadi '', lalu agar tidak terjadi error saya menggunakan method try except karena tidak semua jumlah space pada setiap rows sama, namun pada replace . tidak menggunakan try except karena setiap rows dapat running code tersebut

In [33]:
df['harga'].unique()

array([1500000, 1019400, 1189300,  949500,  545400, 1119200,  999000,
        900000, 1429000, 1000000,  700000, 1099000,  450000,  850000,
        800000,  595000,  659400, 1959300,  799500,  499500, 1540000,
        995400, 1099500,  695200,  677400, 1084300, 2400000,  455400,
        599500, 1560000,  759000,  864500,  779400, 2399000, 2800000,
       2700000, 2199000,  699500, 2499000, 2309300,  749500,  379500,
        649500, 1399300, 1129000,  624500, 1199000, 1783200,  769300,
        737400,  574500, 2699000, 1049500, 1493400,  869000])

Dapat dilihat kembali bahwa value pada column 'harga' sudah berupa nominal yang bersih

In [34]:
df['nama produk'].unique()

array(["\n                    Cloud 6 Women's Sneakers - White                ",
       '\n                    530 Unisex Sneakers - Silver                ',
       '\n                    740 Unisex Sneakers - Beige                ',
       '\n                    740 Unisex Sneakers - Quartz Grey/ Mosaic Green                ',
       "\n                    V5 Rnr Boys' Play School Sneakers - White/Black-Vast Grey-College Grey                ",
       "\n                    V5 RNR Women's Sneakers - Particle Pink/Pale Ivory                ",
       "\n                    V5 RNR Women's Sneakers - White/White-Black                ",
       '\n                    530 Bungee Boys Sneakers - Silver                ',
       "\n                    Samba OG Men's Sneakers - White                ",
       "\n                    P-6000 Men's Sneakers - White/Black-Metallic Silver                ",
       '\n                    Classic Unisex Clog - ATMosphere                ',
       "\n                    Nike Air Max Plus Women's Sneakers - White                ",
       "\n                    Streetball EP Men's Basketball Shoes - LT WILD MANGO/FLASH LIME                ",
       '\n                    Vans Old Skool Unisex Sneakers - BLACK                ',
       '\n                    Handball Spezial Kids Sneakers - Blue                ',
       "\n                    SAMBA OG Kids' Pre-School Sneakers - Ftwr White                ",
       "\n                    GT-2160 Men's Sneakers - Gravel/Carrier Grey                ",
       "\n                    Samba Og Kids' Play School Sneakers - Ftwr White/Powder Plum/Gum5                ",
       '\n                    530 Bungee Boys Kids Sneakers - Beige                ',
       "\n                    GEL-1130 Women's Sneakers - White/Midnight                ",
       "\n                    P-6000 Men's Sneakers - Black                ",
       '\n                    GEL-KINETIC Fluent Unisex Sneakers - White/White                ',
       '\n                    1906 Boys Kids Sneakers - Silver                ',
       '\n                    530 Boys Sneakers - White                ',
       '\n                    Palermo Flat Unisex Sneakers - Bronze-Haute Tropic                ',
       '\n                    530 Bungee Boys Infant Sneakers - Grey                ',
       "\n                    Gazelle Indoor Women's Sneakers - Pink                ",
       "\n                    Cloud 6 Women's Sneakers - Black                ",
       "\n                    Kobe IX Low EM Kids' Grade School Sneakers - Wolf Grey/White                ",
       '\n                    Gel-Cumulus 16 Unisex Sneakers - White/White                ',
       "\n                    Reactx Rejuven8 Kids' Grade School Sandals - Black/Black-Black                ",
       "\n                    Jordan Flight Court Boys' Grade School Basketball Shoes - Black/Gamma Blue                ",
       "\n                    Nike Dunk Low Women's Basketball Shoes - Photon Dust                ",
       "\n                    ON Cloudmonster Women's Running Shoes - All White                ",
       '\n                    Ace Men Casual Shoes - White                ',
       '\n                    Arthur Women Casual Shoes - Pink                ',
       '\n                    327 Boys Kids Sneakers - Black                ',
       "\n                    Nike Air Force 1 '07 Men's Basketball Shoes - White                ",
       "\n                    Dunk Low Retro Men's Basketball Shoes - White                ",
       "\n                    Cloudzone Men's Sneakers - Mulberry/Black                ",
       '\n                    Classic Kids Clog - Pink Milk                ',
       "\n                    TOTAL 90 Men's Sandal - Black/Coconut Milk                ",
       '\n                    740 Boys Kids Sneakers - Black                ',
       '\n                    740 Boys Kids Sneakers - Silver                ',
       "\n                    GEL-NYC 2.0 Men's Sneakers - Graphite Grey/Black                ",
       "\n                    Cloudtilt Women's Sneakers - Her | Dew                ",
       "\n                    Cloudtilt Men's Sneakers - Olive | Desert                ",
       "\n                    Cloudtilt Remix Women's Sneakers - Alloy / Ivory                ",
       "\n                    Cloudtilt Women's Sneakers - Eclipse/ Lilac                ",
       "\n                    Cloudtilt Women's Sneakers - Arctic/ Ice                ",
       '\n                    GEL-CUMULUS 16 Unisex Lifestyle Shoes - Ivory                ',
       "\n                    Vomero 5  Boys' Play School Sneakers - Pearl Pink/Vast Grey                ",
       "\n                    Shox Z Se Women's Sneakers - Particle Rose/Burgundy Crush-Phantom                ",
       "\n                    Rebel V5 Women's Running Shoes - Pink                ",
       '\n                    Pegasus Premium Womens Sneakers - Guava Ice/Sail-Particle Pink                ',
       '\n                    GEL-NYC 2.0 Unisex Sneakers - Cream/Dioptase                ',
       '\n                    GEL-KAYANO 14 Unisex Sneakers - White/Light Navy                ',
       "\n                    Cloudmonster Void Women's Sneakers - Dew/Ivory                ",
       "\n                    Samba OG Elastic I Kids' Infant Sneakers - Core Black                ",
       '\n                    530 Infant Sneakers - Grey                ',
       '\n                    Girls Kids Sneakers - White / Light Pink                ',
       "\n                    Vomero 5 Boys' Grade School Sneakers - Vast Grey/Med Soft Pink-White-White                ",
       "\n                    CTAS Lift Bow Platform Girl's Sneakers - Black/White/Black                ",
       "\n                    Run Star Trainer Women's Sneakers - Incensed/Sporty Berry/Gum                ",
       '\n                    GT-2160 Unisex Sneakers - White/Soft Yellow                ',
       "\n                    P-6000 Kids' Pre-School Sneakers - Black/Black                ",
       "\n                    Nike Air Force 1 Le Boys' Grade School Basketball Shoes - White                ",
       "\n                    Air Jordan 4 Retro Kids' Pre-School Basketball Shoes - Fire Red/White-Black-Cement Grey                ",
       "\n                    Dame X Men's Basketball Shoes - White                ",
       "\n                    Air Jordan 4 Retro Boys' Grade School Basketball Shoes - Photon Dust/Blue Chill                ",
       '\n                    327 Girls Kids Shoes - Pink                ',
       "\n                    Jordan 3 Retro Boys' Play School Basketball Shoes - Medium Olive/Sequoia                ",
       "\n                    Air Jordan 4 Retro Og Boys' Grade School Basketball Shoes - Cave Stone/Black-Phantom                ",
       "\n                    A'One Ep Women'S Basketball Shoes - White/Perfect Pink-Prism Pink-Pink Ice                ",
       "\n                    Ja 2 Ep Men's Basketball Shoes - White/White-White                ",
       '\n                    D.O.N. Issue 6 Unisex Basketball Shoes - Lucid Lemon                ',
       "\n                    Killshot 2 Boys' Grade School Sneakers - White/Black                ",
       "\n                    G.T. Cut 3 Se Kids' Grade School Sneakers - Summit White/Bright Citron-Light Carbon                ",
       "\n                    x SHAI 001 Men's Sneakers - Tickled Pink/Geranium Pink                ",
       "\n                    x SHAI 001 Men's Sneakers - White/White/White                ",
       '\n                    GT-2160 Breeze Unisex Sneakers - White/Pure Silver                ',
       "\n                    Zoom Vomero 5 Men's Sneakers - Wolf Grey/White                ",
       "\n                    Reactx Rejuven8 Kids' Grade School Sandals - Ashen Slate/Ashen Slate                "],
      dtype=object)

Selanjutnya yaitu menampilkan unique value dari column 'nama produk', dapat dilihat juga bahwa value dari rows tersebut belum juga bersih, maka selanjutnya saya akan membersihkan character yang tidak berguna, langkahnya sama seperti pada column 'harga' namun menyesuaikan isi dari rows 'nama produk'

In [35]:
df['nama produk'] = df['nama produk'].str.replace('\n', '')

try:
    df['nama produk'] = df['nama produk'].str.replace('                ', '')
except:
    pass

try:
    df['nama produk'] = df['nama produk'].str.replace('    ', '')
except:
    pass

Melakukan cleaning pada rows 'nama produk' agar data bisa dieksplorasi lebih lanjut

In [36]:
df['nama produk'].unique()

array(["Cloud 6 Women's Sneakers - White", '530 Unisex Sneakers - Silver',
       '740 Unisex Sneakers - Beige',
       '740 Unisex Sneakers - Quartz Grey/ Mosaic Green',
       "V5 Rnr Boys' Play School Sneakers - White/Black-Vast Grey-College Grey",
       "V5 RNR Women's Sneakers - Particle Pink/Pale Ivory",
       "V5 RNR Women's Sneakers - White/White-Black",
       '530 Bungee Boys Sneakers - Silver',
       "Samba OG Men's Sneakers - White",
       "P-6000 Men's Sneakers - White/Black-Metallic Silver",
       'Classic Unisex Clog - ATMosphere',
       "Nike Air Max Plus Women's Sneakers - White",
       "Streetball EP Men's Basketball Shoes - LT WILD MANGO/FLASH LIME",
       'Vans Old Skool Unisex Sneakers - BLACK',
       'Handball Spezial Kids Sneakers - Blue',
       "SAMBA OG Kids' Pre-School Sneakers - Ftwr White",
       "GT-2160 Men's Sneakers - Gravel/Carrier Grey",
       "Samba Og Kids' Play School Sneakers - Ftwr White/Powder Plum/Gum5",
       '530 Bungee Boys Kids Sneakers - Beige',
       "GEL-1130 Women's Sneakers - White/Midnight",
       "P-6000 Men's Sneakers - Black",
       'GEL-KINETIC Fluent Unisex Sneakers - White/White',
       '1906 Boys Kids Sneakers - Silver', '530 Boys Sneakers - White',
       'Palermo Flat Unisex Sneakers - Bronze-Haute Tropic',
       '530 Bungee Boys Infant Sneakers - Grey',
       "Gazelle Indoor Women's Sneakers - Pink",
       "Cloud 6 Women's Sneakers - Black",
       "Kobe IX Low EM Kids' Grade School Sneakers - Wolf Grey/White",
       'Gel-Cumulus 16 Unisex Sneakers - White/White',
       "Reactx Rejuven8 Kids' Grade School Sandals - Black/Black-Black",
       "Jordan Flight Court Boys' Grade School Basketball Shoes - Black/Gamma Blue",
       "Nike Dunk Low Women's Basketball Shoes - Photon Dust",
       "ON Cloudmonster Women's Running Shoes - All White",
       'Ace Men Casual Shoes - White', 'Arthur Women Casual Shoes - Pink',
       '327 Boys Kids Sneakers - Black',
       "Nike Air Force 1 '07 Men's Basketball Shoes - White",
       "Dunk Low Retro Men's Basketball Shoes - White",
       "Cloudzone Men's Sneakers - Mulberry/Black",
       'Classic Kids Clog - Pink Milk',
       "TOTAL 90 Men's Sandal - Black/Coconut Milk",
       '740 Boys Kids Sneakers - Black',
       '740 Boys Kids Sneakers - Silver',
       "GEL-NYC 2.0 Men's Sneakers - Graphite Grey/Black",
       "Cloudtilt Women's Sneakers - Her | Dew",
       "Cloudtilt Men's Sneakers - Olive | Desert",
       "Cloudtilt Remix Women's Sneakers - Alloy / Ivory",
       "Cloudtilt Women's Sneakers - Eclipse/ Lilac",
       "Cloudtilt Women's Sneakers - Arctic/ Ice",
       'GEL-CUMULUS 16 Unisex Lifestyle Shoes - Ivory',
       "Vomero 5  Boys' Play School Sneakers - Pearl Pink/Vast Grey",
       "Shox Z Se Women's Sneakers - Particle Rose/Burgundy Crush-Phantom",
       "Rebel V5 Women's Running Shoes - Pink",
       'Pegasus Premium Womens Sneakers - Guava Ice/Sail-Particle Pink',
       'GEL-NYC 2.0 Unisex Sneakers - Cream/Dioptase',
       'GEL-KAYANO 14 Unisex Sneakers - White/Light Navy',
       "Cloudmonster Void Women's Sneakers - Dew/Ivory",
       "Samba OG Elastic I Kids' Infant Sneakers - Core Black",
       '530 Infant Sneakers - Grey',
       'Girls Kids Sneakers - White / Light Pink',
       "Vomero 5 Boys' Grade School Sneakers - Vast Grey/Med Soft Pink-White-White",
       "CTAS Lift Bow Platform Girl's Sneakers - Black/White/Black",
       "Run Star Trainer Women's Sneakers - Incensed/Sporty Berry/Gum",
       'GT-2160 Unisex Sneakers - White/Soft Yellow',
       "P-6000 Kids' Pre-School Sneakers - Black/Black",
       "Nike Air Force 1 Le Boys' Grade School Basketball Shoes - White",
       "Air Jordan 4 Retro Kids' Pre-School Basketball Shoes - Fire Red/White-Black-Cement Grey",
       "Dame X Men's Basketball Shoes - White",
       "Air Jordan 4 Retro Boys' Grade School Basketball Shoes - Photon Dust/Blue Chill",
       '327 Girls Kids Shoes - Pink',
       "Jordan 3 Retro Boys' Play School Basketball Shoes - Medium Olive/Sequoia",
       "Air Jordan 4 Retro Og Boys' Grade School Basketball Shoes - Cave Stone/Black-Phantom",
       "A'One Ep Women'S Basketball Shoes - White/Perfect Pink-Prism Pink-Pink Ice",
       "Ja 2 Ep Men's Basketball Shoes - White/White-White",
       'D.O.N. Issue 6 Unisex Basketball Shoes - Lucid Lemon',
       "Killshot 2 Boys' Grade School Sneakers - White/Black",
       "G.T. Cut 3 Se Kids' Grade School Sneakers - Summit White/Bright Citron-Light Carbon",
       "x SHAI 001 Men's Sneakers - Tickled Pink/Geranium Pink",
       "x SHAI 001 Men's Sneakers - White/White/White",
       'GT-2160 Breeze Unisex Sneakers - White/Pure Silver',
       "Zoom Vomero 5 Men's Sneakers - Wolf Grey/White",
       "Reactx Rejuven8 Kids' Grade School Sandals - Ashen Slate/Ashen Slate"],
      dtype=object)

Dapat dilihat kembali bahwa column 'nama produk' sudah terlihat bersih

In [37]:
df['merk'].unique()

array(['\nON\n', '\nNEW BALANCE\n', '\nNike\n', '\nADIDAS\n', '\nCROCS\n',
       '\nVANS\n', '\nASICS\n', '\nPUMA\n', '\nELLESSE\n', '\nCONVERSE\n'],
      dtype=object)

Selanjutnya yaitu column 'merk', langkah yang sama seperti 2 column diatas dilakukan untuk membersihkan column 'merk' ini

In [38]:
df['merk'] = df['merk'].str.replace('\n', '')

Melakukan cleaning pada column 'merk'

In [41]:
df['merk'].unique()

array(['ON', 'NEW BALANCE', 'Nike', 'ADIDAS', 'CROCS', 'VANS', 'ASICS',
       'PUMA', 'ELLESSE', 'CONVERSE'], dtype=object)

Dapat dilihat bahwa column 'merk' sudah terlihat bersih dan siap digunakan untuk eksplorasi lebih lanjut

In [39]:
df

,nama produk,merk,harga,kategori,warna
0,Cloud 6 Women's Sneakers - White,ON,1500000,Wanita,Putih
1,530 Unisex Sneakers - Silver,NEW BALANCE,1019400,Unisex,Abu-abu
2,530 Unisex Sneakers - Silver,NEW BALANCE,1189300,Unisex,Abu-abu
3,740 Unisex Sneakers - Beige,NEW BALANCE,949500,Unisex,Beige
4,740 Unisex Sneakers - Quartz Grey/ Mosaic Green,NEW BALANCE,949500,Unisex,Abu-abu
...,...,...,...,...,...
79,x SHAI 001 Men's Sneakers - Tickled Pink/Geran...,CONVERSE,2699000,Pria,Pink
80,x SHAI 001 Men's Sneakers - White/White/White,CONVERSE,2699000,Unisex,Putih
81,GT-2160 Breeze Unisex Sneakers - White/Pure Si...,ASICS,1049500,Unisex,Putih
82,Zoom Vomero 5 Men's Sneakers - Wolf Grey/White,Nike,1493400,Pria,Abu-abu
83,Reactx Rejuven8 Kids' Grade School Sandals - A...,Nike,869000,Anak - Anak,Biru

Menampilkan dataframe kembali dan memastikan semuanya sudah bersih

In [40]:
df.to_csv('data-bersih.csv')

Menyimpan data bersih atau yang sudah selesai eksplorasi dan cleaning ke dalam .csv